name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.OBLAK_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release

